[general]
# import = [
#     "~/.config/alacritty/alacritty/catppuccin-mocha.toml"
# ]

# I don't like the catppuccin-mocha impl here I just took the colors for now
[colors.primary]
background = "#1E1E2E"
foreground = "#CDD6F4"
dim_foreground = "#CDD6F4"
bright_foreground = "#CDD6F4"

[colors.cursor]
text = "#1E1E2E"
cursor = "#F5E0DC"

[colors.vi_mode_cursor]
text = "#1E1E2E"
cursor = "#B4BEFE"

[font]
size = 13

[selection]
save_to_clipboard = true

[keyboard]
bindings = [
    {key = "V", mods = "Control", action = "Paste"},
    {key = "=", mods = "Control", action = "IncreaseFontSize"},
    {key = "-", mods = "Control", action = "DecreaseFontSize"},
    {key = "0", mods = "Control", action = "ResetFontSize"},
    {key = "Back", mods = "Control", chars = "\u0017"},
    {key = "Enter", mods = "Command", action = "ToggleFullscreen"},

    {key = "j", mods = "Command", chars = "\u001Bj"},
    {key = "k", mods = "Command", chars = "\u001Bk"},

    {key = ",", mods = "Command", chars = "\u001B,"},
    {key = ".", mods = "Command", chars = "\u001B."},
    {key = "t", mods = "Command", chars = "\u001Bt"},
    {key = "s", mods = "Command", chars = "\u001Bs"}, 

    {key = "e", mods = "Command", chars = "\u001Be"}, 

    {key = "d", mods = "Command", chars = "\u001Bd"}, 
    {key = "f", mods = "Command", chars = "\u001Bf"}, 
    {key = "h", mods = "Command", chars = "\u001Bh"}, 
    {key = "i", mods = "Command", chars = "\u001Bi"}, 
    {key = "r", mods = "Command", chars = "\u001Br"}, 
    {key = "m", mods = "Command", chars = "\u001Bm"}, 
    {key = "p", mods = "Command", chars = "\u001Bp"}, 
    {key = "w", mods = "Command", chars = "\u001Bw"}, 

]

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "Regular"
